export const REASON_CODE_CATEGORIES = [
    'policy', 'capability', 'consent', 'trust', 'transport', 'compatibility', 'runtime', 'startup', 'telemetry', 'metering', 'payout', 'audit', 'sdk', 'storage', 'governance', 'validation', 'auth', 'execution'
];
export const REASON_CODE_SEVERITIES = ['debug', 'info', 'warn', 'error', 'critical'];
export const REASON_CODE_AUDIENCES = ['internal', 'operator', 'sdk', 'audit', 'user', 'partner', 'telemetry-only'];
export const REASON_CODE_LIFECYCLES = ['experimental', 'stable', 'deprecated', 'internal-only', 'compatibility-only', 'removed'];
export const canonicalReasonCodeRegistry = {
    ACCESS_ALLOWED: { code: 'ACCESS_ALLOWED', category: 'auth', severity: 'info', audience: 'sdk', lifecycle: 'stable', visibility: 'public', owner: 'runtime', classification: 'allow', summary: 'Access approved.', machineMeaning: 'Authorization approved.', explainabilityHint: 'The request satisfied all active authorization checks.', compatibilityNotes: 'Canonical allow outcome.', telemetryClassification: 'decision', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    POLICY_DENY_OVERRIDES: { code: 'POLICY_DENY_OVERRIDES', category: 'policy', severity: 'warn', audience: 'audit', lifecycle: 'stable', visibility: 'public', owner: 'policy', classification: 'deny', summary: 'A deny rule overrode allow matches.', machineMeaning: 'A matched deny effect caused fail-closed denial.', explainabilityHint: 'One or more deny rules matched and deny has precedence.', compatibilityNotes: 'Use for deterministic deny precedence.', telemetryClassification: 'decision', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    POLICY_INDETERMINATE_FAIL_CLOSED: { code: 'POLICY_INDETERMINATE_FAIL_CLOSED', category: 'policy', severity: 'error', audience: 'operator', lifecycle: 'stable', visibility: 'restricted', owner: 'policy', classification: 'deny', summary: 'Policy evaluation became indeterminate under fail-closed mode.', machineMeaning: 'Protected operation denied because policy evaluation failed safely.', explainabilityHint: 'At least one policy condition evaluation failed and protected operation requires deny.', compatibilityNotes: 'Canonical safe default when evaluation cannot complete.', telemetryClassification: 'health', sdkExposurePolicy: 'public-compat', auditSafe: true, telemetryOnly: false },
    TRUST_INVALID: { code: 'TRUST_INVALID', category: 'trust', severity: 'warn', audience: 'sdk', lifecycle: 'stable', visibility: 'public', owner: 'security', classification: 'deny', summary: 'Trust verification failed.', machineMeaning: 'Identity or trust chain did not pass validation.', explainabilityHint: 'Trust posture checks failed or were incomplete.', compatibilityNotes: 'Use as normalized trust deny.', telemetryClassification: 'decision', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    CAPABILITY_EXPIRED: { code: 'CAPABILITY_EXPIRED', category: 'capability', severity: 'warn', audience: 'sdk', lifecycle: 'stable', visibility: 'public', owner: 'runtime', classification: 'deny', summary: 'Capability is expired.', machineMeaning: 'Capability validity window has ended.', explainabilityHint: 'Capability expiry timestamp is in the past.', compatibilityNotes: 'Canonical capability expiry deny.', telemetryClassification: 'decision', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    CONSENT_EXPIRED: { code: 'CONSENT_EXPIRED', category: 'consent', severity: 'warn', audience: 'sdk', lifecycle: 'stable', visibility: 'public', owner: 'runtime', classification: 'deny', summary: 'Consent is expired.', machineMeaning: 'Parent consent validity window has ended.', explainabilityHint: 'Consent expiry timestamp is in the past.', compatibilityNotes: 'Canonical consent expiry deny.', telemetryClassification: 'decision', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    TRANSPORT_VERSION_UNSUPPORTED: { code: 'TRANSPORT_VERSION_UNSUPPORTED', category: 'transport', severity: 'error', audience: 'partner', lifecycle: 'stable', visibility: 'public', owner: 'platform', classification: 'deny', summary: 'Transport protocol version is unsupported.', machineMeaning: 'Inbound transport version is outside accepted compatibility range.', explainabilityHint: 'Upgrade caller to a supported transport version.', compatibilityNotes: 'Maps legacy compatibility transport failures.', telemetryClassification: 'transport', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    SDK_RUNTIME_COMPATIBILITY_WARNING: { code: 'SDK_RUNTIME_COMPATIBILITY_WARNING', category: 'compatibility', severity: 'warn', audience: 'sdk', lifecycle: 'stable', visibility: 'public', owner: 'sdk', classification: 'warning', summary: 'SDK/runtime compatibility warning.', machineMeaning: 'Execution proceeds with degraded compatibility guarantees.', explainabilityHint: 'Version combination is tolerated but not preferred.', compatibilityNotes: 'For non-fatal compatibility drift.', telemetryClassification: 'compatibility', sdkExposurePolicy: 'public-stable', auditSafe: true, telemetryOnly: false },
    STARTUP_UNSAFE_CONFIGURATION: { code: 'STARTUP_UNSAFE_CONFIGURATION', category: 'startup', severity: 'critical', audience: 'operator', lifecycle: 'stable', visibility: 'restricted', owner: 'platform', classification: 'error', summary: 'Startup safety assertion failed.', machineMeaning: 'Runtime configuration violates required startup invariants.', explainabilityHint: 'Correct configuration and restart runtime.', compatibilityNotes: 'Canonical startup hard-fail indicator.', telemetryClassification: 'health', sdkExposurePolicy: 'internal', auditSafe: true, telemetryOnly: false },
    TELEMETRY_REDACTION_APPLIED: { code: 'TELEMETRY_REDACTION_APPLIED', category: 'telemetry', severity: 'info', audience: 'telemetry-only', lifecycle: 'stable', visibility: 'internal', owner: 'platform', classification: 'status', summary: 'Telemetry payload redaction applied.', machineMeaning: 'Sensitive attributes were removed before emit.', explainabilityHint: 'Payload was emitted with redaction safeguards.', compatibilityNotes: 'Telemetry-only operational signal.', telemetryClassification: 'audit', sdkExposurePolicy: 'internal', auditSafe: true, telemetryOnly: true },
    INTERNAL_EVALUATION_ERROR: { code: 'INTERNAL_EVALUATION_ERROR', category: 'runtime', severity: 'error', audience: 'internal', lifecycle: 'internal-only', visibility: 'internal', owner: 'runtime', classification: 'error', summary: 'Internal evaluation error.', machineMeaning: 'Unhandled internal evaluation exception occurred.', explainabilityHint: 'Inspect runtime logs and trace identifiers.', compatibilityNotes: 'Must not be exposed directly in stable external SDK contracts.', telemetryClassification: 'health', sdkExposurePolicy: 'internal', auditSafe: false, telemetryOnly: false },
};
export const legacyReasonCodeAliases = {
    POLICY_DENIED: 'POLICY_DENY_OVERRIDES',
    ACCESS_DENIED_NOT_FOUND: 'TRUST_INVALID',
    ACCESS_DENIED_ISSUER_INACTIVE: 'TRUST_INVALID',
    ACCESS_DENIED_EXPIRED: 'TRUST_INVALID',
    ACCESS_DENIED_REVOKED: 'TRUST_INVALID',
    ACCESS_DENIED_CONSENT_REQUIRED: 'TRUST_INVALID',
};
export function getReasonCode(code) {
    const canonical = legacyReasonCodeAliases[code] ?? code;
    return canonicalReasonCodeRegistry[canonical];
}
export function normalizeReasonCode(code) { return getReasonCode(code)?.code ?? code; }
export function classifyReasonCode(code) { return getReasonCode(code)?.classification ?? 'unknown'; }
export function isStableReasonCode(code) { return getReasonCode(code)?.lifecycle === 'stable'; }
export function isSdkSafeReasonCode(code) { const e = getReasonCode(code); return !!e && e.sdkExposurePolicy !== 'internal' && e.lifecycle !== 'internal-only' && e.visibility !== 'internal'; }
export function isAuditSafeReasonCode(code) { return getReasonCode(code)?.auditSafe === true; }
export function isDeprecatedReasonCode(code) { return getReasonCode(code)?.lifecycle === 'deprecated'; }
