export const ENFORCEMENT_REASON_CODES = {
    CAPABILITY_INVALID: 'CAPABILITY_INVALID',
    CAPABILITY_EXPIRED: 'CAPABILITY_EXPIRED',
    CAPABILITY_REVOKED: 'CAPABILITY_REVOKED',
    CAPABILITY_NOT_YET_ACTIVE: 'CAPABILITY_NOT_YET_ACTIVE',
    SCOPE_NOT_ALLOWED: 'SCOPE_NOT_ALLOWED',
    PERMISSION_NOT_ALLOWED: 'PERMISSION_NOT_ALLOWED',
    SUBJECT_MISMATCH: 'SUBJECT_MISMATCH',
    GRANTEE_MISMATCH: 'GRANTEE_MISMATCH',
    MARKET_MAKER_MISMATCH: 'MARKET_MAKER_MISMATCH',
    REQUEST_INVALID: 'REQUEST_INVALID',
    ENFORCEMENT_ALLOW: 'ENFORCEMENT_ALLOW',
};
