import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const renderDocsPage = () => {
    return (_jsxs("main", { className: "min-h-screen bg-[#0a0a0a] text-white font-sans", children: [_jsx("section", { className: "border-b border-white/10", children: _jsxs("div", { className: "mx-auto max-w-6xl px-6 py-20 md:py-24", children: [_jsx("p", { className: "text-[11px] uppercase tracking-[0.24em] text-cyan-300/70", children: "AOC Protocol Documentation" }), _jsx("h1", { className: "mt-4 text-5xl font-semibold tracking-tight md:text-6xl", children: "Build on a consent-native control plane." }), _jsx("p", { className: "mt-6 max-w-3xl text-lg leading-8 text-white/65", children: "AOC gives applications and enterprises a programmable layer for consent, policy, capabilities, governed execution, and auditability." })] }) }), _jsx("section", { id: "getting-started", className: "border-b border-white/10", children: _jsxs("div", { className: "mx-auto max-w-6xl px-6 py-16", children: [_jsx("h2", { className: "text-3xl font-semibold tracking-tight", children: "Getting started" }), _jsxs("div", { className: "mt-8 grid gap-5 md:grid-cols-3", children: [_jsxs("article", { className: "rounded-2xl border border-white/10 bg-white/[0.03] p-6", children: [_jsx("p", { className: "text-sm font-semibold text-cyan-200", children: "1. Define permissions" }), _jsx("p", { className: "mt-3 text-sm leading-7 text-white/65", children: "Model what can be accessed, by whom, and under which conditions." })] }), _jsxs("article", { className: "rounded-2xl border border-white/10 bg-white/[0.03] p-6", children: [_jsx("p", { className: "text-sm font-semibold text-cyan-200", children: "2. Evaluate requests" }), _jsx("p", { className: "mt-3 text-sm leading-7 text-white/65", children: "Route each request through consent, policy, identity, and capability checks." })] }), _jsxs("article", { className: "rounded-2xl border border-white/10 bg-white/[0.03] p-6", children: [_jsx("p", { className: "text-sm font-semibold text-cyan-200", children: "3. Enforce + audit" }), _jsx("p", { className: "mt-3 text-sm leading-7 text-white/65", children: "Execute only approved actions and record every decision path for traceability." })] })] })] }) }), _jsx("section", { className: "border-b border-white/10", children: _jsxs("div", { className: "mx-auto max-w-6xl px-6 py-16", children: [_jsx("h2", { className: "text-3xl font-semibold tracking-tight", children: "Core concepts" }), _jsx("div", { className: "mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-5", children: [
                                ['Consent', 'Explicit approval boundaries.'],
                                ['Policy', 'Rules that shape permitted behavior.'],
                                ['Identity', 'Who or what is requesting access.'],
                                ['Capabilities', 'Machine-scoped actions with strict limits.'],
                                ['Audit', 'Permanent record of outcomes and reasoning.'],
                            ].map(([title, body]) => (_jsxs("article", { className: "rounded-2xl border border-white/10 bg-white/[0.03] p-5", children: [_jsx("h3", { className: "text-base font-semibold text-white", children: title }), _jsx("p", { className: "mt-3 text-sm leading-7 text-white/65", children: body })] }, title))) })] }) }), _jsx("section", { className: "border-b border-white/10", children: _jsxs("div", { className: "mx-auto max-w-6xl px-6 py-16", children: [_jsx("h2", { className: "text-3xl font-semibold tracking-tight", children: "Enterprise integration" }), _jsx("p", { className: "mt-5 max-w-4xl text-base leading-8 text-white/65", children: "AOC can sit in front of existing systems as a governed decision layer for requests, permissions, machine actions, and auditability across sensitive workflows." }), _jsx("div", { className: "mt-8", children: _jsx("a", { href: "/?view=enterprise", className: "inline-flex items-center justify-center rounded-xl border border-cyan-300/40 px-6 py-3 text-sm font-semibold text-cyan-200 transition hover:border-cyan-300/70 hover:bg-cyan-300/10", children: "Go to Enterprise page" }) })] }) }), _jsx("section", { className: "py-16", children: _jsx("div", { className: "mx-auto max-w-6xl px-6", children: _jsxs("div", { className: "rounded-3xl border border-white/10 bg-white/[0.03] p-8 md:p-10", children: [_jsx("h2", { className: "text-3xl font-semibold tracking-tight", children: "Documentation v1" }), _jsx("p", { className: "mt-4 max-w-3xl text-base leading-8 text-white/65", children: "This page is the first dedicated internal docs surface for AOC Protocol. It can expand into a full docs site with architecture, integration, and developer sections." }), _jsx("div", { className: "mt-8 flex flex-col gap-3 sm:flex-row", children: _jsx("a", { href: "/?view=landing", className: "inline-flex items-center justify-center rounded-xl border border-white/15 px-6 py-3 text-sm font-semibold text-white/85 transition hover:border-white/30 hover:text-white", children: "Back to landing" }) })] }) }) })] }));
};
