export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type ConsentSubjectType = 'user' | 'workspace' | 'service_account' | 'agent';
export type ConsentStatus = 'granted' | 'denied' | 'expired' | 'revoked' | 'superseded';
export type RevocationReason = 'user_request' | 'admin_action' | 'policy_change' | 'legal_request' | 'security_event' | 'system_cleanup';
export type AudienceType = 'static' | 'dynamic' | 'computed';

export interface Database {
  public: {
    Tables: {
      tenants: { Row: { id: string; tenant_key: string; display_name: string; created_at: string }; Insert: { id?: string; tenant_key: string; display_name: string; created_at?: string }; Update: Partial<{ id: string; tenant_key: string; display_name: string; created_at: string }> };
      audiences: { Row: { id: string; tenant_id: string; audience_key: string; name: string; description: string | null; audience_type: AudienceType; filter_definition: Json | null; lifecycle_state: string; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; deleted_at: string | null }; Insert: { id?: string; tenant_id: string; audience_key: string; name: string; description?: string | null; audience_type?: AudienceType; filter_definition?: Json | null; lifecycle_state?: string; created_by?: string | null; updated_by?: string | null; created_at?: string; updated_at?: string; deleted_at?: string | null }; Update: Partial<Database['public']['Tables']['audiences']['Insert']> };
      audience_members: { Row: { id: string; tenant_id: string; audience_id: string; subject_type: ConsentSubjectType; subject_id: string; membership_source: string; source_ref: string | null; valid_from: string; valid_to: string | null; created_by: string | null; created_at: string }; Insert: { id?: string; tenant_id: string; audience_id: string; subject_type: ConsentSubjectType; subject_id: string; membership_source?: string; source_ref?: string | null; valid_from?: string; valid_to?: string | null; created_by?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['audience_members']['Insert']> };
      consent_scopes: { Row: { id: string; tenant_id: string; scope_key: string; scope_name: string; scope_description: string | null; legal_basis: string | null; data_categories: string[]; processor_purposes: string[]; risk_level: number; is_sensitive: boolean; version: number; previous_scope_id: string | null; is_active: boolean; metadata: Json; created_by: string | null; created_at: string; updated_at: string }; Insert: { id?: string; tenant_id: string; scope_key: string; scope_name: string; scope_description?: string | null; legal_basis?: string | null; data_categories?: string[]; processor_purposes?: string[]; risk_level?: number; is_sensitive?: boolean; version?: number; previous_scope_id?: string | null; is_active?: boolean; metadata?: Json; created_by?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['consent_scopes']['Insert']> };
      user_consents: { Row: { id: string; tenant_id: string; subject_type: ConsentSubjectType; subject_id: string; scope_id: string; scope_version: number; status: ConsentStatus; granted_at: string | null; denied_at: string | null; source_channel: string; source_event_id: string | null; proof_hash: string | null; policy_snapshot: Json; metadata: Json; created_at: string; updated_at: string }; Insert: { id?: string; tenant_id: string; subject_type?: ConsentSubjectType; subject_id: string; scope_id: string; scope_version: number; status: ConsentStatus; granted_at?: string | null; denied_at?: string | null; source_channel: string; source_event_id?: string | null; proof_hash?: string | null; policy_snapshot?: Json; metadata?: Json; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['user_consents']['Insert']> };
    }
  }
}
