export const CONSENT_DECISION_REASON_CODES = {
    ALLOW: 'ALLOW',
    DENY_NO_CONSENT: 'DENY_NO_CONSENT',
    DENY_SUBJECT_MISMATCH: 'DENY_SUBJECT_MISMATCH',
    DENY_REQUESTER_MISMATCH: 'DENY_REQUESTER_MISMATCH',
    DENY_RESOURCE_MISMATCH: 'DENY_RESOURCE_MISMATCH',
    DENY_ACTION_NOT_GRANTED: 'DENY_ACTION_NOT_GRANTED',
    DENY_NOT_GRANTED: 'DENY_NOT_GRANTED',
    DENY_EXPIRED: 'DENY_EXPIRED',
    DENY_REVOKED: 'DENY_REVOKED',
    DENY_INVALID_INPUT: 'DENY_INVALID_INPUT',
};
